### ISSUE TITLE
Organizing GitHub repository

### ISSUE THREAD

**Issue by Baklap4** [loic-sharma/BaGet#58]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I expected to see:
- [ ] a project to be defined within the GitHub section.
- [ ] milestones created
- [ ] some labels to attach to issues
- [ ] Rebase pr onto master as only merge option for PR's
- [ ] default branch (master) to be locked and can only be modified by PR's (also by admins)

#### Projects
This is a section on GitHub to create a scrumboard like swimminglanes (To-Do, In Progress, Done).
This in combination with Milestones (which are to be added aswell) creates a feeling to the user about when something is in progress or even done. This way we can also create a roadmap between versions.

Aside from this board i'd create another project board called `Backlog` with items to be picked up in another version of BaGet.

#### Milestones
Milestones can be assigned to issues. This will indicate what we're doing just as the projects are doing. Since the issue list is more viewed than the Projects section it's beneficial milestones as versions are added here aswell.

#### Labels
Labels indicate what an issue is about, it may be a bug, a feature, enhancement anything.

#### Rebase PR's
As shown in this [pr](https://github.com/loic-sharma/BaGet/pull/54#discussion_r202160453)
> I've just thought as per these rules you...
    - Should have just one item in your pr
    - Can have multiple commits to present the feature/bugfix/etc
    - Besides above commits, have review commits which can be squashed together after all review messages have been done (creating a new squashed commit containing the git messages from these changes).
    - Run `git rebase -i origin/master` to make sure there's unessairy stuff in.
    - Click rebase and merge button in github
    This seperates the feature commits and the review commits. And makes sure no items from master is within this pr
